### ISSUE TITLE
Make Web Interface

### ISSUE THREAD

**Issue by EMurtaghh** [EMurtaghh/SpringBootDemo#6]

**Comment by CryptoGraphicDragon** [comment]
Git Projects
	Git projects is able to handle all aspects of github integration and issue management, but it quite clunky. Tags must be created and changed manually, comments are not easy to find, and most issue information can only be accessed by leaving the board. While it has many of the desired features, it takes a few extra steps to do anything.

Trello
	While aesthetically pleasing, Trello has limited features that can be implemented without spending money. You get one free “power-up” which can be used either for burndown charts, github integration, or anything else. With the help of the free Chrome extension Scrum for Trello, adding times and summing totals for lists is easy, but not perfect. Each sprint would also require a new board as there is no way to differentiate sprints in the burndown charts available. Overall, Trello is nice but far from optimal.

Zenhub
	The most similar to Waffle that we have currently found. It contains many different ways to chart and organize, while also being connected to github, and updating in real time. All comments are easy to read and updates can be linked to slack. You still have to manually create and change tags on issues, but it is easy to do.
